apiVersion: v1
kind: Secret
metadata:
  name: application-secret-{{BRANCH_NAME}}            #{{BRANCH_NAME}} --> Place Holder which will be replaced by BranchName at run time to keep the code DRY
  namespace: kubernetes-cluster-gaurankgoyal
type: Opaque
data:
  username: bXktc2VjcmV0LXVzZXJuYW1l          #Base 64 Encoded Password
  password: bXktc3VwZXItc2VjcmV0LXBhc3M=      #Base 64 Encoded Password