apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  namespace: kubernetes-cluster-gaurankgoyal
type: Opaque
data:
  username: bXktc2VjcmV0LXVzZXJuYW1l
  password: bXktc3VwZXItc2VjcmV0LXBhc3M=