#{{BRANCH_NAME}} --> Place Holder which will be replaced by BranchName at run time to keep the code DRY
apiVersion: v1
kind: Service
metadata:
  name: lb-service-{{BRANCH_NAME}}
  namespace: kubernetes-cluster-gaurankgoyal
spec:
  selector:
    app: app_gaurankgoyal_{{BRANCH_NAME}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer