apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: kubernetes-cluster-gaurankgoyal
spec:
  selector:
    app: app_gaurankgoyal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer